// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvuAPkn6TUvY5iAHVntzfqNkinjFTv62Q',
    appId: '1:876196456698:web:71ba7c2848169681af0143',
    messagingSenderId: '876196456698',
    projectId: 'labmid-c9064',
    authDomain: 'labmid-c9064.firebaseapp.com',
    storageBucket: 'labmid-c9064.appspot.com',
    measurementId: 'G-XQDQGVSLX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC90ybBMJbu953nPf0mB5qssBM4qwqOKsI',
    appId: '1:876196456698:android:b634175e7705eedcaf0143',
    messagingSenderId: '876196456698',
    projectId: 'labmid-c9064',
    storageBucket: 'labmid-c9064.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6Q5idp9N-1k02TX-3174S4tBsh5B71c0',
    appId: '1:876196456698:ios:b755f4cb570a9aa2af0143',
    messagingSenderId: '876196456698',
    projectId: 'labmid-c9064',
    storageBucket: 'labmid-c9064.appspot.com',
    iosBundleId: 'com.example.labMid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6Q5idp9N-1k02TX-3174S4tBsh5B71c0',
    appId: '1:876196456698:ios:14d86537fbf0033caf0143',
    messagingSenderId: '876196456698',
    projectId: 'labmid-c9064',
    storageBucket: 'labmid-c9064.appspot.com',
    iosBundleId: 'com.example.labMid.RunnerTests',
  );
}
